### ISSUE TITLE
Does not work with version 8.

### ISSUE THREAD

**Issue by ajohnstone** [danielb2/blipp#3]
```

/home/andrew/Desktop/projects/github/photobox/services/service-members/node_modules/hapi/node_modules/hoek/lib/index.js:663
    throw new Error(msgs.join(' ') || 'Unknown error');
          ^
Error: A callback function is required to register a plugin
    at Object.exports.assert (/home/andrew/Desktop/projects/github/photobox/services/service-members/node_modules/hapi/node_modules/hoek/lib/index.js:663:11)
    at internals.Plugin.register (/home/andrew/Desktop/projects/github/photobox/services/service-members/node_modules/hapi/lib/plugin.js:154:10)
    at Object.<anonymous> (/home/andrew/Desktop/projects/github/photobox/services/service-members/server.js:16:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3

```

**Comment by AdrieanKhisbe** [comment]
Should Update the documentation. On v8 (on v8....), you load the plugin with 
`server.register`. (I had the same issue)

    server.register({register: require('myplugin')}, function (err) {
         if (err) {
             console.error('Failed to load plugin:', err);
         }
     });

(can do it by fork&Pr if needed

**Comment by danielb2** [comment]
Ah, thank you much. I had published the npm, but had missed merging it back into master.
