### ISSUE TITLE
showScope option throwing an error

### ISSUE THREAD

**Issue by BryceLarkin** [danielb2/blipp#33]
Using typescript. Registering blipp with this option configuration: 
```javascript
 {
    plugin: require("blipp"),
    options: { showAuth: true, showScope: true }
  }
```

Getting this error (took out my root directory):

```javascript
Unhandled rejection { AssertionError [ERR_ASSERTION]: {
  "showAuth": true,
  "showScope" [1]: true
}

[1] "showScope" is not allowed
    at new AssertionError (/internal/assert.js:268:11)
    at Object.exports.assert (/node_modules/hoek/lib/index.js:736:11)
    at Object.exports.register (/node_modules/blipp/lib/index.js:20:10)
    at internals.Server.register (/node_modules/hapi/lib/server.js:431:35)
    at init (/index.ts:17:16)
    at Object.<anonymous> (/index.ts:45:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module.m._compile (/node_modules/ts-node/src/index.ts:439:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/node_modules/ts-node/src/index.ts:442:12)
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '==' }
```

edit: I'm using blipp version 3.0.0

**Comment by danielb2** [comment]
the version with showScope hasn't been released yet. Check https://www.npmjs.com/package/blipp  to see what the latest release is. I'm working on cleaning up the display since it's getting to be cluttered so I am adding headers.
